// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_ZAPATA_ATENCIA_MANUELA.DAL;

#nullable disable

namespace Parcial2_ZAPATA_ATENCIA_MANUELA.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230402162929_IndexID_Entitytbl")]
    partial class IndexID_Entitytbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial2_ZAPATA_ATENCIA_MANUELA.DAL.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Entity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Parcial2_ZAPATA_ATENCIA_MANUELA.DAL.Entities.ConcertDB", b =>
                {
                    b.HasBaseType("Parcial2_ZAPATA_ATENCIA_MANUELA.DAL.Entities.Entity");

                    b.Property<string>("EntranceGate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("ConcertDB");
                });
#pragma warning restore 612, 618
        }
    }
}
